"""Short `amp` command for creating and running a default local agent team."""
from __future__ import annotations

import getpass
import json
import os
import re
import shlex
import subprocess
from pathlib import Path
from typing import Any

import click
import httpx

from agent_mailer_cli.config import Config, save_config

DEFAULT_BROKER_URL = "http://localhost:9800"
DEFAULT_CREDENTIALS_PATH = Path.home() / ".agent-mailer" / "credentials.json"
DEFAULT_PERMISSION_MODE = "acceptEdits"

DEFAULT_TEAM_AGENTS = [
    {
        "suffix": "planner",
        "role": "planner",
        "description": "Requirement breakdown and architecture planning",
        "prompt_template": (
            "你是需求分析与架构设计专家。收到自然语言需求后，先拆解为清晰的技术规格，"
            "包括模块划分、接口设计、验收标准和风险点。\n"
            "需要别人继续处理时，主动通过 Mail Broker 发邮件协作。拆解完成后 forward 给 "
            "{coder}，并 reply 通知发起人当前状态。"
        ),
    },
    {
        "suffix": "coder",
        "role": "coder",
        "description": "Code implementation",
        "prompt_template": (
            "你是软件开发者。收到技术规格后实现代码、补充必要测试，并在本地验证。\n"
            "需要澄清时主动 reply 给发起人或 {planner}。完成实现后 reply 给 {reviewer} "
            "申请审查；不要把未审查成品直接 forward 到下游。"
        ),
    },
    {
        "suffix": "reviewer",
        "role": "reviewer",
        "description": "Code review",
        "prompt_template": (
            "你是代码审查专家。审查正确性、安全性、可维护性、测试覆盖和回归风险。\n"
            "发现问题时 reply 给 {coder}，附具体修改意见；通过后 reply 给 {planner}，"
            "并 forward 给 {runner} 做执行验证。"
        ),
    },
    {
        "suffix": "runner",
        "role": "runner",
        "description": "Validation and deployment checks",
        "prompt_template": (
            "你是执行验证专家。负责运行测试、部署 staging、做 smoke check，并记录关键命令和结果。\n"
            "验证完成后 reply 给 {planner} 汇报最终状态；如果失败，reply 给 {coder} 和 "
            "{reviewer} 说明失败点。"
        ),
    },
]

_TEAM_NAME_RE = re.compile(r"[^a-z0-9_-]+")
_GITIGNORE_ENTRIES = ["agents/", ".agent-mailer/", "team.yaml", "start-team.sh", "stop-team.sh"]


def normalize_team_name(raw: str) -> str:
    name = _TEAM_NAME_RE.sub("-", raw.lower()).strip("-_")
    if not name:
        name = "team"
    if not re.match(r"^[a-z0-9]", name):
        name = f"team-{name}"
    return name[:31].rstrip("-_") or "team"


def render_team_yaml(team: str, broker_url: str, permission_mode: str) -> str:
    names = _agent_names(team)
    lines = [
        "# Generated by amp init. Re-run amp init to refresh local agent files.",
        f"team: {team}",
        f"broker_url: {broker_url}",
        "runtime: agent-mailer watch",
        f"permission_mode: {permission_mode}",
        "agents:",
    ]
    for spec in DEFAULT_TEAM_AGENTS:
        full_name = names[spec["suffix"]]
        prompt = spec["prompt_template"].format(**names)
        lines.extend([
            f"  - name: {full_name}",
            f"    role: {spec['role']}",
            f"    description: {spec['description']}",
            "    system_prompt: |",
        ])
        lines.extend(f"      {line}" for line in prompt.splitlines())
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _agent_names(team: str) -> dict[str, str]:
    return {spec["suffix"]: f"{team}_{spec['suffix']}" for spec in DEFAULT_TEAM_AGENTS}


def _credentials_path(path: str | None) -> Path:
    return Path(path).expanduser() if path else DEFAULT_CREDENTIALS_PATH


def _load_credentials(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {"credentials": {}}
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {"credentials": {}}
    if not isinstance(data, dict):
        return {"credentials": {}}
    data.setdefault("credentials", {})
    return data


def _save_credentials(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2))
    os.chmod(tmp, 0o600)
    os.replace(tmp, path)


def _normalize_url(url: str) -> str:
    return url.rstrip("/")


def _resolve_broker_url(broker_url: str | None, creds: dict[str, Any]) -> str:
    if broker_url:
        return _normalize_url(broker_url)
    env_url = os.environ.get("AMP_BROKER_URL")
    if env_url:
        return _normalize_url(env_url)
    saved = creds.get("default_broker_url")
    if isinstance(saved, str) and saved:
        return _normalize_url(saved)
    if click.get_text_stream("stdin").isatty():
        raw = click.prompt("Broker URL", default=DEFAULT_BROKER_URL, show_default=True)
        return _normalize_url(raw)
    return DEFAULT_BROKER_URL


def _login(
    *,
    broker_url: str,
    username: str | None,
    password: str | None,
    credentials_path: Path,
    client: httpx.Client,
) -> tuple[str, str]:
    creds = _load_credentials(credentials_path)
    entry = creds.get("credentials", {}).get(broker_url)
    if isinstance(entry, dict) and entry.get("token") and entry.get("username"):
        return str(entry["token"]), str(entry["username"])

    if not username:
        if not click.get_text_stream("stdin").isatty():
            raise click.ClickException(
                f"Not logged in to {broker_url}. Re-run with --username or set AMP_USERNAME."
            )
        username = click.prompt(f"Username for {broker_url}")
    password = password or os.environ.get("AMP_PASSWORD")
    if not password:
        password = getpass.getpass(f"Password for {username}: ")
    if not password:
        raise click.ClickException("Password is required.")

    resp = client.post(f"{broker_url}/users/login", json={"username": username, "password": password})
    if resp.status_code != 200:
        raise click.ClickException(f"Login failed ({resp.status_code}): {resp.text}")
    token = resp.json()["token"]
    creds.setdefault("credentials", {})[broker_url] = {"username": username, "token": token}
    creds["default_broker_url"] = broker_url
    _save_credentials(credentials_path, creds)
    return token, username


def _api(client: httpx.Client, method: str, url: str, *, token: str, **kwargs) -> Any:
    headers = kwargs.pop("headers", {})
    headers["Authorization"] = f"Bearer {token}"
    resp = client.request(method, url, headers=headers, **kwargs)
    if resp.status_code >= 400:
        raise click.ClickException(f"{method} {url} failed ({resp.status_code}): {resp.text}")
    return resp.json()


def _ensure_team(client: httpx.Client, broker_url: str, token: str, team: str) -> str:
    teams = _api(client, "GET", f"{broker_url}/admin/teams", token=token)
    for item in teams:
        if item.get("name") == team:
            return item["id"]
    created = _api(
        client,
        "POST",
        f"{broker_url}/admin/teams",
        token=token,
        json={"name": team, "description": "Default amp planner/coder/reviewer/runner team"},
    )
    return created["id"]


def _render_agent_prompt(team: str, suffix: str) -> str:
    names = _agent_names(team)
    spec = next(item for item in DEFAULT_TEAM_AGENTS if item["suffix"] == suffix)
    return spec["prompt_template"].format(**names)


def _ensure_agent(
    client: httpx.Client,
    broker_url: str,
    token: str,
    *,
    team: str,
    team_id: str,
    spec: dict[str, str],
) -> dict[str, str]:
    name = f"{team}_{spec['suffix']}"
    prompt = _render_agent_prompt(team, spec["suffix"])
    agents = _api(client, "GET", f"{broker_url}/users/me/agents", token=token)
    existing = next((item for item in agents if item.get("name") == name), None)
    if existing:
        agent_id = existing["id"]
        _api(
            client,
            "PUT",
            f"{broker_url}/users/me/agents/{agent_id}",
            token=token,
            json={
                "role": spec["role"],
                "description": spec["description"],
                "system_prompt": prompt,
                "team_id": team_id,
            },
        )
        key = _api(
            client,
            "POST",
            f"{broker_url}/users/me/agents/{agent_id}/regenerate-key",
            token=token,
        )["api_key_plaintext"]
        agent = _api(client, "GET", f"{broker_url}/users/me/agents/{agent_id}", token=token)
    else:
        created = _api(
            client,
            "POST",
            f"{broker_url}/users/me/agents",
            token=token,
            json={
                "name": name,
                "address_local": name,
                "role": spec["role"],
                "description": spec["description"],
                "system_prompt": prompt,
                "team_id": team_id,
            },
        )
        key = created["api_key_plaintext"]
        agent = created

    exported = _api(
        client,
        "GET",
        f"{broker_url}/users/me/agents/{agent['id']}/export",
        token=token,
        params={"format": "agent_md"},
    )
    return {
        "id": agent["id"],
        "name": agent["name"],
        "address": agent["address"],
        "api_key": key,
        "agent_md": exported["content"],
    }


def _write_gitignore(out_dir: Path) -> None:
    path = out_dir / ".gitignore"
    text = path.read_text() if path.exists() else ""
    lines = set(text.splitlines())
    additions = [item for item in _GITIGNORE_ENTRIES if item not in lines]
    if not additions:
        return
    out = text
    if out and not out.endswith("\n"):
        out += "\n"
    if out:
        out += "\n"
    out += "# agent-mailer local team artifacts\n" + "\n".join(additions) + "\n"
    path.write_text(out)


def _write_launchers(out_dir: Path, team: str, agent_names: list[str]) -> None:
    session = f"amp-{team}"
    windows = "\n".join(
        _tmux_window_line(session, name, i == 0) for i, name in enumerate(agent_names)
    )
    start = f"""#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
SESSION={session!r}

if ! command -v tmux >/dev/null 2>&1; then
  echo "Error: tmux is required to start the team." >&2
  exit 1
fi

if tmux has-session -t "$SESSION" 2>/dev/null; then
  exec tmux attach -t "$SESSION"
fi

{windows}

exec tmux attach -t "$SESSION"
"""
    stop = f"""#!/usr/bin/env bash
set -euo pipefail
SESSION={session!r}
if tmux has-session -t "$SESSION" 2>/dev/null; then
  tmux kill-session -t "$SESSION"
  echo "Stopped $SESSION."
else
  echo "Session $SESSION is not running."
fi
"""
    start_path = out_dir / "start-team.sh"
    stop_path = out_dir / "stop-team.sh"
    start_path.write_text(start)
    stop_path.write_text(stop)
    os.chmod(start_path, 0o755)
    os.chmod(stop_path, 0o755)


def _tmux_window_line(session: str, name: str, first: bool) -> str:
    cwd = f"agents/{name}"
    cmd = "agent-mailer watch"
    if first:
        return f"tmux new-session -d -s \"$SESSION\" -n {name!r} -c {cwd!r} {cmd!r}"
    return f"tmux new-window -t \"$SESSION\" -n {name!r} -c {cwd!r} {cmd!r}"


def create_default_team(
    *,
    out_dir: Path,
    team: str,
    broker_url: str,
    token: str,
    permission_mode: str,
    client: httpx.Client,
) -> list[dict[str, str]]:
    out_dir.mkdir(parents=True, exist_ok=True)
    team_id = _ensure_team(client, broker_url, token, team)
    agents: list[dict[str, str]] = []
    for spec in DEFAULT_TEAM_AGENTS:
        agent = _ensure_agent(client, broker_url, token, team=team, team_id=team_id, spec=spec)
        agent_dir = out_dir / "agents" / agent["name"]
        agent_dir.mkdir(parents=True, exist_ok=True)
        (agent_dir / "AGENT.md").write_text(agent["agent_md"])
        save_config(
            Config(
                workdir=agent_dir,
                agent_id=agent["id"],
                agent_name=agent["name"],
                address=agent["address"],
                broker_url=broker_url,
                api_key=agent["api_key"],
                permission_mode=permission_mode,
            )
        )
        agents.append(agent)

    (out_dir / "team.yaml").write_text(render_team_yaml(team, broker_url, permission_mode))
    _write_launchers(out_dir, team, [agent["name"] for agent in agents])
    _write_gitignore(out_dir)
    return agents


def _path_from_name(name: str) -> Path:
    path = Path(name).expanduser()
    if path.is_absolute() or path.parent != Path("."):
        return path.resolve()
    return (Path.cwd() / normalize_team_name(name)).resolve()


def _resolve_target_dir(name: str | None, out_dir: Path | None) -> Path:
    if out_dir is not None:
        return out_dir.expanduser().resolve()
    if name:
        return _path_from_name(name)
    return Path.cwd().resolve()


def _resolve_team_name(name: str | None, team: str | None, target: Path) -> str:
    if team:
        return normalize_team_name(team)
    if name:
        return normalize_team_name(Path(name).name)
    return normalize_team_name(target.name)


def _initialize_team(
    *,
    name: str | None,
    team: str | None,
    out_dir: Path | None,
    broker_url: str | None,
    username: str | None,
    password: str | None,
    permission_mode: str,
    credentials_path: str | None,
) -> tuple[Path, str, str, str, list[dict[str, str]]]:
    target = _resolve_target_dir(name, out_dir)
    team_name = _resolve_team_name(name, team, target)
    cred_path = _credentials_path(credentials_path)
    creds = _load_credentials(cred_path)
    resolved_broker = _resolve_broker_url(broker_url, creds)
    with httpx.Client(timeout=30.0) as client:
        token, user = _login(
            broker_url=resolved_broker,
            username=username or os.environ.get("AMP_USERNAME"),
            password=password,
            credentials_path=cred_path,
            client=client,
        )
        agents = create_default_team(
            out_dir=target,
            team=team_name,
            broker_url=resolved_broker,
            token=token,
            permission_mode=permission_mode,
            client=client,
        )
    return target, team_name, resolved_broker, user, agents


def _command_target(name: str | None, out_dir: Path | None) -> str:
    if out_dir is not None:
        return f"--dir {shlex.quote(str(out_dir))}"
    if name:
        return shlex.quote(name)
    return ""


def _command_with_target(command: str, name: str | None, out_dir: Path | None) -> str:
    target = _command_target(name, out_dir)
    if target:
        return f"amp {command} {target}"
    return f"amp {command}"


def _print_init_summary(
    *,
    target: Path,
    team_name: str,
    broker_url: str,
    user: str,
    agents: list[dict[str, str]],
    start_command: str,
    stop_command: str,
) -> None:
    click.echo(f"OK Team '{team_name}' ready in {target}")
    click.echo(f"OK Broker: {broker_url} ({user})")
    for agent in agents:
        click.echo(f"  - {agent['name']} - {agent['address']}")
    click.echo(f"\nStart: {start_command}")
    click.echo(f"Stop:  {stop_command}")


@click.group(help="amp — one-command local Agent Mailer team launcher.")
def cli() -> None:
    pass


@cli.command("login", help="Remember broker login for future amp commands.")
@click.argument("broker", required=False)
@click.argument("username_arg", required=False)
@click.option("--broker-url", default=None, help="Broker URL.")
@click.option("--username", default=None, help="Login username.")
@click.option("--password", default=None, hide_input=True, help="Login password; prefer AMP_PASSWORD.")
@click.option("--credentials-path", default=None, hidden=True)
def login(
    broker: str | None,
    username_arg: str | None,
    broker_url: str | None,
    username: str | None,
    password: str | None,
    credentials_path: str | None,
) -> None:
    cred_path = _credentials_path(credentials_path)
    creds = _load_credentials(cred_path)
    resolved_broker = _resolve_broker_url(broker_url or broker, creds)
    with httpx.Client(timeout=30.0) as client:
        _, user = _login(
            broker_url=resolved_broker,
            username=username or username_arg or os.environ.get("AMP_USERNAME"),
            password=password,
            credentials_path=cred_path,
            client=client,
        )
    click.echo(f"OK Logged in to {resolved_broker} as {user}")


@cli.command("init", help="Create the default planner/coder/reviewer/runner team.")
@click.argument("name", required=False)
@click.option("--team", default=None, help="Team prefix (default: current directory name).")
@click.option("--dir", "out_dir", type=click.Path(file_okay=False, path_type=Path), default=None,
              help="Team directory (default: ./NAME, or current directory without NAME).")
@click.option("--broker-url", default=None, help="Broker URL (defaults to saved login, then localhost).")
@click.option("--username", default=None, help="Login username when no saved session exists.")
@click.option("--password", default=None, hide_input=True, help="Login password; prefer AMP_PASSWORD.")
@click.option("--permission-mode", type=click.Choice(["acceptEdits", "bypassPermissions", "plan"]),
              default=DEFAULT_PERMISSION_MODE, show_default=True)
@click.option("--credentials-path", default=None, hidden=True)
def init(name: str | None, team: str | None, out_dir: Path | None, broker_url: str | None,
         username: str | None, password: str | None, permission_mode: str,
         credentials_path: str | None) -> None:
    target, team_name, resolved_broker, user, agents = _initialize_team(
        name=name,
        team=team,
        out_dir=out_dir,
        broker_url=broker_url,
        username=username,
        password=password,
        permission_mode=permission_mode,
        credentials_path=credentials_path,
    )
    _print_init_summary(
        target=target,
        team_name=team_name,
        broker_url=resolved_broker,
        user=user,
        agents=agents,
        start_command=_command_with_target("start", name, out_dir),
        stop_command=_command_with_target("stop", name, out_dir),
    )


@cli.command("up", help="Create or refresh a team, then start it.")
@click.argument("name", required=False)
@click.option("--team", default=None, help="Team prefix (default: NAME or directory name).")
@click.option("--dir", "out_dir", type=click.Path(file_okay=False, path_type=Path), default=None,
              help="Team directory (default: ./NAME, or current directory without NAME).")
@click.option("--broker-url", default=None, help="Broker URL (defaults to saved login, then localhost).")
@click.option("--username", default=None, help="Login username when no saved session exists.")
@click.option("--password", default=None, hide_input=True, help="Login password; prefer AMP_PASSWORD.")
@click.option("--permission-mode", type=click.Choice(["acceptEdits", "bypassPermissions", "plan"]),
              default=DEFAULT_PERMISSION_MODE, show_default=True)
@click.option("--credentials-path", default=None, hidden=True)
def up(name: str | None, team: str | None, out_dir: Path | None, broker_url: str | None,
       username: str | None, password: str | None, permission_mode: str,
       credentials_path: str | None) -> None:
    target, team_name, resolved_broker, user, agents = _initialize_team(
        name=name,
        team=team,
        out_dir=out_dir,
        broker_url=broker_url,
        username=username,
        password=password,
        permission_mode=permission_mode,
        credentials_path=credentials_path,
    )
    _print_init_summary(
        target=target,
        team_name=team_name,
        broker_url=resolved_broker,
        user=user,
        agents=agents,
        start_command=_command_with_target("start", name, out_dir),
        stop_command=_command_with_target("stop", name, out_dir),
    )
    _run_script(target, "start-team.sh")


@cli.command("start", help="Start this local team in tmux.")
@click.argument("name", required=False)
@click.option("--dir", "out_dir", type=click.Path(file_okay=False, path_type=Path), default=None,
              help="Team directory (default: ./NAME, or current directory without NAME).")
def start(name: str | None, out_dir: Path | None) -> None:
    _run_script(_resolve_target_dir(name, out_dir), "start-team.sh")


@cli.command("stop", help="Stop this local team.")
@click.argument("name", required=False)
@click.option("--dir", "out_dir", type=click.Path(file_okay=False, path_type=Path), default=None,
              help="Team directory (default: ./NAME, or current directory without NAME).")
def stop(name: str | None, out_dir: Path | None) -> None:
    _run_script(_resolve_target_dir(name, out_dir), "stop-team.sh")


def _run_script(out_dir: Path, name: str) -> None:
    script = out_dir.resolve() / name
    if not script.exists():
        raise click.ClickException(f"{script} not found. Run `amp init` first.")
    subprocess.run([str(script)], cwd=out_dir.resolve(), check=True)


cli.add_command(init, "new")


if __name__ == "__main__":
    cli()
